################################################################################
# DIRECTORIES
################################################################################

# Define the root directory
ROOT_DIR ?= $(shell pwd)
export ROOT_DIR

# Directory for the output binaries
BUILD_DIR ?= $(ROOT_DIR)/build
export BUILD_DIR

# Source code root directory
SRC_ROOT_DIR ?= $(ROOT_DIR)/src
export SRC_ROOT_DIR

# Generated source code root directory
SRC_GEN_DIR ?= $(ROOT_DIR)/src/generated-cxx
export SRC_GEN_DIR

# Generated source code root directory
CSRC_GEN_DIR ?= $(ROOT_DIR)/src/generated-c
export CSRC_GEN_DIR

# Helper scripts directory
SCRIPTS_DIR ?= $(ROOT_DIR)/scripts
export SCRIPTS_DIR

# Externals (libraries) directory
EXT_DIR ?= $(ROOT_DIR)/ext
export EXT_DIR

################################################################################
# INCLUDES
################################################################################

INCLUDES = -I$(SRC_ROOT_DIR) -I$(SRC_GEN_DIR) -I$(CSRC_GEN_DIR)

################################################################################
# LIBRARIES
################################################################################

LIBS += -lgflags -lglog -lboost_system -lboost_thread -lboost_regex -lprotobuf

################################################################################
# COMPILER
################################################################################

CXX = clang++
CXX_RELEASE := $(shell whereis clang++ | awk '{split( $$0, a, ":"); print a[ 2]}')
ifeq ( $(CXX_RELEASE), )
	CXX = g++
endif

OPTFLAGS = -g -O0
#OPTFLAGS = -O3

CPPFLAGS = $(INCLUDES) -std=c++11 -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-long-long -Wno-variadic-macros -Wno-unused-function -Wno-vla

################################################################################
# PROTOBUF COMPILER
################################################################################

PBC = protoc

PBCC = protoc-c

PBCFLAGS =

################################################################################
# MAKE
################################################################################

MAKE = make

MAKEFLAGS = --no-print-directory
